list = [];
const Aatrox = new Champion("Aatrox", false, false, false, false, false, true, false, false, false, false, false, [""], "resources\\icons\\icon (1).webp");
const Ahri = new Champion("Ahri", false, false, false, false, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (2).webp");
const Akali = new Champion("Akali", false, false, false, false, false, false, false, false, true, false, false, ["ionia"], "resources\\icons\\icon (3).webp");
const Akshan = new Champion("Akshan", false, true, true, false, false, false, false, true, true, false, false, ["shurima"], "resources\\icons\\icon (4).webp");
const Alistar = new Champion("Alistar", false, false, false, true, true, true, false, true, false, false, false, [""], "resources\\icons\\icon (5).webp");
const Amumu = new Champion("Amumu", true, false, false, false, false, true, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (6).webp");
const Anivia = new Champion("Anivia", false, false, false, false, false, true, false, true, false, false, true, ["freljord"], "resources\\icons\\icon (7).webp");
const Annie = new Champion("Annie", true, false, false, true, false, false, false, false, false, true, false, [""], "resources\\icons\\icon (8).webp");
const Aphelios = new Champion("Aphelios", false, false, false, false, false, false, false, false, false, false, false, ["targon"], "resources\\icons\\icon (9).webp");
const Ashe = new Champion("Ashe", false, true, true, false, false, false, false, false, false, false, false, ["freljord"], "resources\\icons\\icon (10).webp");
const Aurelion_Sol = new Champion("Aurelion Sol", true, false, false, false, true, true, false, false, false, false, false, ["targon"], "resources\\icons\\icon (11).webp");
const Azir = new Champion("Azir", true, true, false, false, true, false, false, false, false, true, true, ["shurima"], "resources\\icons\\icon (12).webp");
const Bard = new Champion("Bard", true, false, true, true, false, true, false, true, false, false, false, [""], "resources\\icons\\icon (13).webp");
const Bel_Veth = new Champion("Bel'Veth", true, false, false, false, false, false, false, true, false, false, false, ["void"], "resources\\icons\\icon (14).webp");
const Blitzcrank = new Champion("Blitzcrank", true, false, false, false, true, true, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (15).webp");
const Brand = new Champion("Brand", false, false, false, false, false, false, false, false, false, false, false, [""], "resources\\icons\\icon (16).webp");
const Braum = new Champion("Braum", true, false, false, false, false, true, false, true, false, false, false, ["freljord"], "resources\\icons\\icon (17).webp");
const Caitlyn = new Champion("Caitlyn", false, true, true, false, false, false, true, false, false, false, false, ["piltover"], "resources\\icons\\icon (18).webp");
const Camille = new Champion("Camille", false, false, false, false, false, true, false, false, false, false, false, ["piltover"], "resources\\icons\\icon (19).webp");
const Cassiopeia = new Champion("Cassiopeia", true, false, false, false, false, false, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (20).webp");
const Cho_Gath = new Champion("Cho'Gath", false, true, false, false, false, false, false, false, false, false, false, ["void"], "resources\\icons\\icon (21).webp");
const Corki = new Champion("Corki", true, true, false, false, false, false, false, false, false, false, false, ["bandleCity", "piltover"], "resources\\icons\\icon (22).webp");
const Darius = new Champion("Darius", false, false, false, false, true, false, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (23).webp");
const Diana = new Champion("Diana", true, false, false, false, false, false, false, false, false, false, false, ["targon"], "resources\\icons\\icon (24).webp");
const Dr_Mundo = new Champion("Dr. Mundo", false, true, false, false, false, false, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (25).webp");
const Draven = new Champion("Draven", true, false, true, false, false, false, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (26).webp");
const Ekko = new Champion("Ekko", true, false, false, false, false, false, false, true, false, false, false, ["zaun"], "resources\\icons\\icon (27).webp");
const Elise = new Champion("Elise", false, false, false, false, false, false, false, true, false, true, false, ["shadowIsles"], "resources\\icons\\icon (28).webp");
const Evelynn = new Champion("Evelynn", false, false, false, false, false, false, false, true, true, false, false, ["shadowIsles"], "resources\\icons\\icon (29).webp");
const Ezreal = new Champion("Ezreal", true, true, true, false, false, false, false, false, false, false, false, ["piltover"], "resources\\icons\\icon (30).webp");
const Fiddlesticks = new Champion("Fiddlesticks", true, false, false, false, false, false, false, false, false, true, false, ["shadowIsles"], "resources\\icons\\icon (31).webp");
const Fiora = new Champion("Fiora", false, false, false, true, false, false, false, true, false, false, false, ["demacia"], "resources\\icons\\icon (32).webp");
const Fizz = new Champion("Fizz", true, false, false, false, false, false, false, true, false, false, false, ["bilgewater", "bandleCity"], "resources\\icons\\icon (33).webp");
const Galio = new Champion("Galio", true, false, true, true, false, true, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (34).webp");
const Gangplank = new Champion("Gangplank", true, true, true, false, false, false, true, false, false, false, false, ["bilgewater"], "resources\\icons\\icon (35).webp");
const Garen = new Champion("Garen", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (36).webp");
const Gnar = new Champion("Gnar", true, false, false, false, true, true, false, false, false, false, false, ["bandleCity", "freljord"], "resources\\icons\\icon (37).webp");
const Gragas = new Champion("Gragas", true, false, false, false, true, true, false, false, false, false, false, ["freljord"], "resources\\icons\\icon (38).webp");
const Graves = new Champion("Graves", true, false, false, false, false, false, false, false, false, false, false, ["bilgewater"], "resources\\icons\\icon (39).webp");
const Gwen = new Champion("Gwen", false, false, false, false, false, false, false, true, false, false, false, ["shadowIsles"], "resources\\icons\\icon (40).webp");
const Hecarim = new Champion("Hecarim", true, false, false, false, true, true, false, false, false, false, false, ["shadowIsles"], "resources\\icons\\icon (41).webp");
const Heimerdinger = new Champion("Heimerdinger", true, false, false, false, false, false, false, false, false, true, false, ["bandleCity", "piltover"], "resources\\icons\\icon (42).webp");
const Illaoi = new Champion("Illaoi", true, false, false, false, false, false, false, false, false, true, false, ["bilgewater"], "resources\\icons\\icon (43).webp");
const Irelia = new Champion("Irelia", false, false, false, false, false, false, false, false, false, false, true, ["ionia"], "resources\\icons\\icon (44).webp");
const Ivern = new Champion("Ivern", false, false, false, true, false, true, false, false, false, true, true, ["ionia"], "resources\\icons\\icon (45).webp");
const Janna = new Champion("Janna", true, false, false, true, true, true, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (46).webp");
const Jarvan_IV = new Champion("Jarvan IV", true, false, false, false, false, true, false, false, false, false, true, ["demacia"], "resources\\icons\\icon (47).webp");
const Jax = new Champion("Jax", false, false, false, false, false, false, false, true, false, false, false, [""], "resources\\icons\\icon (48).webp");
const Jayce = new Champion("Jayce", false, true, false, false, true, false, false, false, false, false, false, ["piltover"], "resources\\icons\\icon (49).webp");
const Jhin = new Champion("Jhin", false, true, true, false, false, false, true, false, false, false, false, ["ionia"], "resources\\icons\\icon (50).webp");
const Jinx = new Champion("Jinx", true, true, true, false, false, false, true, false, false, false, false, ["zaun"], "resources\\icons\\icon (51).webp");
const Kai_Sa = new Champion("Kai'Sa", false, true, true, false, false, false, false, false, true, false, false, ["void"], "resources\\icons\\icon (52).webp");
const Kalista = new Champion("Kalista", false, false, false, false, false, false, false, true, false, true, false, ["shadowIsles"], "resources\\icons\\icon (53).webp");
const Karma = new Champion("Karma", false, true, false, true, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (54).webp");
const Karthus = new Champion("Karthus", true, false, true, false, false, false, false, true, false, false, false, ["shadowIsles"], "resources\\icons\\icon (55).webp");
const Kassadin = new Champion("Kassadin", false, false, false, false, false, false, false, false, false, false, false, ["void"], "resources\\icons\\icon (56).webp");
const Katarina = new Champion("Katarina", true, false, false, false, false, false, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (57).webp");
const Kayle = new Champion("Kayle", true, false, false, true, false, false, false, true, false, false, false, ["demacia"], "resources\\icons\\icon (58).webp");
const Kayn = new Champion("Kayn", false, false, false, false, false, false, false, true, false, false, false, ["ionia"], "resources\\icons\\icon (59).webp");
const Kennen = new Champion("Kennen", true, false, false, false, false, false, false, false, false, false, false, ["bandleCity", "ionia"], "resources\\icons\\icon (60).webp");
const Kha_Zix = new Champion("Kha'Zix", false, false, false, false, false, false, false, false, true, false, false, ["void"], "resources\\icons\\icon (61).webp");
const Kindred = new Champion("Kindred", false, false, false, true, false, false, false, true, false, true, false, [""], "resources\\icons\\icon (62).webp");
const Kled = new Champion("Kled", false, true, true, false, true, true, false, true, false, false, false, ["bandleCity"], "resources\\icons\\icon (63).webp");
const Kog_Maw = new Champion("Kog'Maw", false, true, false, false, false, false, false, true, false, false, false, ["void"], "resources\\icons\\icon (64).webp");
const LeBlanc = new Champion("LeBlanc", false, false, false, false, false, true, false, false, true, false, false, ["noxus"], "resources\\icons\\icon (65).webp");
const Lee_Sin = new Champion("Lee Sin", false, false, false, true, true, false, false, false, false, false,  false, ["ionia"], "resources\\icons\\icon (66).webp");
const Leona = new Champion("Leona", true, false, false, false, false, true, false, false, false, false, false, ["targon"], "resources\\icons\\icon (67).webp");
const Lillia = new Champion("Lillia", false, false, true, false, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (68).webp");
const Lissandra = new Champion("Lissandra", true, false, false, false, false, true, false, true, false, true, false, ["freljord"], "resources\\icons\\icon (69).webp");
const Lucian = new Champion("Lucian", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (70).webp");
const Lulu = new Champion("Lulu", false, false, false, true, false, true, false, false, false, false, false, ["bandleCity"], "resources\\icons\\icon (71).webp");
const Lux = new Champion("Lux", true, true, true, true, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (72).webp");
const Malphite = new Champion("Malphite", true, false, false, false, false, false, false, false, false, false, false, ["ixtal"], "resources\\icons\\icon (73).webp");
const Malzahar = new Champion("Malzahar", false, false, false, false, false, false, false, true, false, true, false, ["void"], "resources\\icons\\icon (74).webp");
const Maokai = new Champion("Maokai", true, true, true, false, true, true, true, true, false, true, false, ["shadowIsles"], "resources\\icons\\icon (75).webp");
const Master_Yi = new Champion("Master Yi", false, false, false, false, false, false, false, true, false, false, false, ["ionia"], "resources\\icons\\icon (76).webp");
const Miss_Fortune = new Champion("Miss Fortune", true, false, false, false, false, false, false, false, false, false, false, ["bilgewater"], "resources\\icons\\icon (78).webp");
const Mordekaiser = new Champion("Mordekaiser", false, false, false, false, true, false, false, false, false, false, false, [""], "resources\\icons\\icon (79).webp");
const Morgana = new Champion("Morgana", true, false, false, true, false, true, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (80).webp");
const Nami = new Champion("Nami", true, false, false, true, false, true, false, false, false, false, false, [""], "resources\\icons\\icon (81).webp");
const Nasus = new Champion("Nasus", false, false, false, false, false, false, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (82).webp");
const Nautilus = new Champion("Nautilus", false, false, false, false, true, true, false, false, false, false, false, ["bilgewater"], "resources\\icons\\icon (83).webp");
const Neeko = new Champion("Neeko", true, false, false, false, false, true, false, false, true, true, false, ["ixtal"], "resources\\icons\\icon (84).webp");
const Nidalee = new Champion("Nidalee", false, true, false, true, false, false, true, false, false, false, false, ["ixtal"], "resources\\icons\\icon (85).webp");
const Nilah = new Champion("Nilah", true, false, false, true, true, false, false, false, false, false, false, [""], "resources\\icons\\icon (164).webp");
const Nocturne = new Champion("Nocturne", false, false, true, false, false, false, false, false, true, false, false, [""], "resources\\icons\\icon (86).webp");
const Nunu_Willump = new Champion("Nunu & Willump", true, false, false, false, false, true, false, false, false, false, false, ["freljord"], "resources\\icons\\icon (87).webp");
const Olaf = new Champion("Olaf", false, false, false, false, false, false, false, true, false, false, false, ["freljord"], "resources\\icons\\icon (88).webp");
const Orianna = new Champion("Orianna", true, false, false, true, true, false, false, false, false, true, false, ["piltover"], "resources\\icons\\icon (89).webp");
const Ornn = new Champion("Ornn", true, false, false, false, false, true, false, false, false, false, true, ["freljord"], "resources\\icons\\icon (90).webp");
const Pantheon = new Champion("Pantheon", true, true, true, false, false, false, false, true, false, false, false, ["targon"], "resources\\icons\\icon (91).webp");
const Poppy = new Champion("Poppy", false, false, false, false, true, true, false, false, false, false, false, ["bandleCity", "demacia"], "resources\\icons\\icon (92).webp");
const Pyke = new Champion("Pyke", false, false, false, false, true, true, false, false, true, false, false, ["bilgewater"], "resources\\icons\\icon (93).webp");
const Qiyana = new Champion("Qiyana", true, false, false, false, false, true, false, false, true, false, false, ["ixtal"], "resources\\icons\\icon (94).webp");
const Quinn = new Champion("Quinn", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (95).webp");
const Rakan = new Champion("Rakan", true, false, false, true, false, false, false, true, false, false, false, ["ionia"], "resources\\icons\\icon (96).webp");
const Rammus = new Champion("Rammus", true, false, false, false, false, true, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (97).webp");
const Rek_Sai = new Champion("Rek'Sai", false, false, false, false, false, false, false, false, false, false, false, ["void"], "resources\\icons\\icon (98).webp");
const Rell = new Champion("Rell", true, false, false, true, true, true, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (99).webp");
const Renata_Glasc = new Champion("Renata Glasc", true, false, false, true, false, true, false, true, false, false, false, ["zaun"], "resources\\icons\\icon (161).webp");
const Renekton = new Champion("Renekton", false, false, false, false, false, false, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (100).webp");
const Rengar = new Champion("Rengar", false, false, false, false, false, false, false, false, true, false, false, ["ixtal"], "resources\\icons\\icon (101).webp");
const Riven = new Champion("Riven", true, false, false, false, false, true, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (103).webp");
const Rumble = new Champion("Rumble", true, false, false, false, false, false, false, false, false, false, false, ["bandleCity"], "resources\\icons\\icon (104).webp");
const Ryze = new Champion("Ryze", false, false, true, false, false, false, false, false, false, false, false, [""], "resources\\icons\\icon (105).webp");
const Samira = new Champion("Samira", true, false, false, false, false, false, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (106).webp");
const Sejuani = new Champion("Sejuani", true, false, false, false, false, true, false, false, false, false, false, ["freljord"], "resources\\icons\\icon (107).webp");
const Senna = new Champion("Senna", true, true, true, true, false, false, false, false, true, false, false, ["shadowIsles"], "resources\\icons\\icon (108).webp");
const Seraphine = new Champion("Seraphine", true, true, false, true, false, true, false, false, false, false, false, ["piltover"], "resources\\icons\\icon (109).webp");
const Sett = new Champion("Sett", true, false, false, false, true, true, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (110).webp");
const Shaco = new Champion("Shaco", false, false, false, false, false, true, true, false, true, true, false, [""], "resources\\icons\\icon (111).webp");
const Shen = new Champion("Shen", false, false, true, true, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (113).webp");
const Shyvana = new Champion("Shyvana", false, true, false, false, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (114).webp");
const Singed = new Champion("Singed", false, false, false, false, true, true, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (115).webp");
const Sion = new Champion("Sion", false, false, true, false, false, true, false, true, false, false, false, ["noxus"], "resources\\icons\\icon (116).webp");
const Sivir = new Champion("Sivir", false, true, false, false, false, false, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (117).webp");
const Skarner = new Champion("Skarner", false, false, false, false, true, true, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (118).webp");
const Sona = new Champion("Sona", true, false, false, true, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (119).webp");
const Soraka = new Champion("Soraka", false, false, true, true, false, false, false, false, false, false, false, ["targon"], "resources\\icons\\icon (120).webp");
const Swain = new Champion("Swain", true, false, true, false, true, false, false, false, false, false, false, ["noxus"], "resources\\icons\\icon (121).webp");
const Sylas = new Champion("Sylas", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "resources\\icons\\icon (122).webp");
const Syndra = new Champion("Syndra", false, false, false, false, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (123).webp");
const Tahm_Kench = new Champion("Tahm Kench", false, false, false, true, true, true, false, true, false, false, false, ["bilgewater"], "resources\\icons\\icon (124).webp");
const Taliyah = new Champion("Taliyah", false, true, true, false, true, false, false, false, false, false, true, ["shurima"], "resources\\icons\\icon (125).webp");
const Talon = new Champion("Talon", true, false, false, false, false, false, false, false, true, false, false, ["noxus"], "resources\\icons\\icon (126).webp");
const Taric = new Champion("Taric", false, false, false, true, false, false, false, true, false, false, false, ["targon"], "resources\\icons\\icon (127).webp");
const Teemo = new Champion("Teemo", false, false, false, false, false, false, true, false, true, false, false, ["bandleCity"], "resources\\icons\\icon (128).webp");
const Thresh = new Champion("Thresh", false, false, false, true, true, true, false, false, false, false, false, ["shadowIsles"], "resources\\icons\\icon (129).webp");
const Tristana = new Champion("Tristana", false, false, false, false, true, false, false, false, false, false, false, ["bandleCity"], "resources\\icons\\icon (130).webp");
const Trundle = new Champion("Trundle", false, false, false, false, false, false, false, false, false, false, true, ["freljord"], "resources\\icons\\icon (131).webp");
const Tryndamere = new Champion("Tryndamere", false, false, false, false, false, false, false, true, false, false, false, ["freljord"], "resources\\icons\\icon (132).webp");
const Twisted_Fate = new Champion("Twisted Fate", false, true, true, false, false, false, false, false, false, false, false, ["bilgewater"], "resources\\icons\\icon (133).webp");
const Twitch = new Champion("Twitch", true, false, false, false, false, false, false, false, true, false, false, ["zaun"], "resources\\icons\\icon (134).webp");
const Udyr = new Champion("Udyr", false, false, false, false, false, false, false, false, false, false, false, ["freljord"], "resources\\icons\\icon (135).webp");
const Urgot = new Champion("Urgot", false, false, false, false, true, true, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (136).webp");
const Varus = new Champion("Varus", false, true, false, false, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (137).webp");
const Vayne = new Champion("Vayne", false, false, false, false, true, false, false, false, true, false, false, ["demacia"], "resources\\icons\\icon (138).webp");
const Veigar = new Champion("Veigar", false, false, false, false, false, false, false, false, false, false, true, ["bandleCity"], "resources\\icons\\icon (139).webp");
const Vel_Koz = new Champion("Vel'Koz", true, true, false, false, false, false, false, false, false, false, false, ["void"], "resources\\icons\\icon (140).webp");
const Vex = new Champion("Vex", false, true, true, false, false, false, false, false, false, false, false, ["bandleCity"], "resources\\icons\\icon (163).webp");
const Vi = new Champion("Vi", false, false, false, false, false, true, false, false, false, false, false, ["piltover"], "resources\\icons\\icon (141).webp");
const Viego = new Champion("Viego", false, false, false, false, false, false, false, false, true, false, false, ["shadowIsles"], "resources\\icons\\icon (142).webp");
const Viktor = new Champion("Viktor", true, true, false, false, false, false, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (143).webp");
const Vladimir = new Champion("Vladimir", true, false, false, false, false, false, false, true, false, false, false, ["noxus"], "resources\\icons\\icon (144).webp");
const Volibear = new Champion("Volibear", true, false, false, false, false, false, false, false, false, false, false, ["freljord"], "resources\\icons\\icon (145).webp");
const Warwick = new Champion("Warwick", false, false, false, false, false, true, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (146).webp");
const Wukong = new Champion("Wukong", false, false, false, false, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (147).webp");
const Xayah = new Champion("Xayah", true, true, false, false, false, false, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (148).webp");
const Xerath = new Champion("Xerath", false, true, true, false, false, false, false, false, false, false, false, ["shurima"], "resources\\icons\\icon (149).webp");
const Xin_Zhao = new Champion("Xin Zhao", true, false, false, false, true, true, false, true, false, false, false, ["demacia"], "resources\\icons\\icon (150).webp");
const Yasuo = new Champion("Yasuo", false, false, false, false, false, true, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (151).webp");
const Yone = new Champion("Yone", true, false, false, false, true, true, false, false, false, false, false, ["ionia"], "resources\\icons\\icon (152).webp");
const Yorick = new Champion("Yorick", false, false, false, false, false, false, false, false, false, true, true, ["shadowIsles"], "resources\\icons\\icon (153).webp");
const Yuumi = new Champion("Yuumi", true, true, false, true, false, false, false, true, false, false, false, ["bandleCity"], "resources\\icons\\icon (154).webp");
const Zac = new Champion("Zac", true, false, false, false, true, true, false, true, false, false, false, ["zaun"], "resources\\icons\\icon (155).webp");
const Zed = new Champion("Zed", false, false, false, false, false, false, false, true, false, true, false, ["ionia"], "resources\\icons\\icon (156).webp");
const Zeri = new Champion("Zeri", false, false, false, false, false, false, false, false, false, false, false, ["zaun"], "resources\\icons\\icon (162).webp");
const Ziggs = new Champion("Ziggs", true, true, true, false, true, false, true, false, false, false, false, ["bandleCity"], "resources\\icons\\icon (157).webp");
const Zilean = new Champion("Zilean", false, false, false, true, false, false, false, true, false, false, false, ["shurima"], "resources\\icons\\icon (158).webp");
const Zoe = new Champion("Zoe", false, true, false, false, false, false, false, false, false, false, false, ["targon"], "resources\\icons\\icon (159).webp");
const Zyra = new Champion("Zyra", true, false, false, false, false, true, true, false, false, true, false, ["ixtal"], "resources\\icons\\icon (160).webp");
list.push(Aatrox);
list.push(Ahri);
list.push(Akali);
list.push(Akshan);
list.push(Alistar);
list.push(Amumu);
list.push(Anivia);
list.push(Annie);
list.push(Aphelios);
list.push(Ashe);
list.push(Aurelion_Sol);
list.push(Azir);
list.push(Bard);
list.push(Bel_Veth);
list.push(Blitzcrank);
list.push(Brand);
list.push(Braum);
list.push(Caitlyn);
list.push(Camille);
list.push(Cassiopeia);
list.push(Cho_Gath);
list.push(Corki);
list.push(Darius);
list.push(Diana);
list.push(Dr_Mundo);
list.push(Draven);
list.push(Ekko);
list.push(Elise);
list.push(Evelynn);
list.push(Ezreal);
list.push(Fiddlesticks);
list.push(Fiora);
list.push(Fizz);
list.push(Galio);
list.push(Gangplank);
list.push(Garen);
list.push(Gnar);
list.push(Gragas);
list.push(Graves);
list.push(Gwen);
list.push(Hecarim);
list.push(Heimerdinger);
list.push(Illaoi);
list.push(Irelia);
list.push(Ivern);
list.push(Janna);
list.push(Jarvan_IV);
list.push(Jax);
list.push(Jayce);
list.push(Jhin);
list.push(Jinx);
list.push(Kai_Sa);
list.push(Kalista);
list.push(Karma);
list.push(Karthus);
list.push(Kassadin);
list.push(Katarina);
list.push(Kayle);
list.push(Kayn);
list.push(Kennen);
list.push(Kha_Zix);
list.push(Kindred);
list.push(Kled);
list.push(Kog_Maw);
list.push(LeBlanc);
list.push(Lee_Sin);
list.push(Leona);
list.push(Lillia);
list.push(Lissandra);
list.push(Lucian);
list.push(Lulu);
list.push(Lux);
list.push(Malphite);
list.push(Malzahar);
list.push(Maokai);
list.push(Master_Yi);
list.push(Miss_Fortune);
list.push(Mordekaiser);
list.push(Morgana);
list.push(Nami);
list.push(Nasus);
list.push(Nautilus);
list.push(Neeko);
list.push(Nidalee);
list.push(Nilah);
list.push(Nocturne);
list.push(Nunu_Willump);
list.push(Olaf);
list.push(Orianna);
list.push(Ornn);
list.push(Pantheon);
list.push(Poppy);
list.push(Pyke);
list.push(Qiyana);
list.push(Quinn);
list.push(Rakan);
list.push(Rammus);
list.push(Rek_Sai);
list.push(Rell);
list.push(Renata_Glasc);
list.push(Renekton);
list.push(Rengar);
list.push(Riven);
list.push(Rumble);
list.push(Ryze);
list.push(Samira);
list.push(Sejuani);
list.push(Senna);
list.push(Seraphine);
list.push(Sett);
list.push(Shaco);
list.push(Shen);
list.push(Shyvana);
list.push(Singed);
list.push(Sion);
list.push(Sivir);
list.push(Skarner);
list.push(Sona);
list.push(Soraka);
list.push(Swain);
list.push(Sylas);
list.push(Syndra);
list.push(Tahm_Kench);
list.push(Taliyah);
list.push(Talon);
list.push(Taric);
list.push(Teemo);
list.push(Thresh);
list.push(Tristana);
list.push(Trundle);
list.push(Tryndamere);
list.push(Twisted_Fate);
list.push(Twitch);
list.push(Udyr);
list.push(Urgot);
list.push(Varus);
list.push(Vayne);
list.push(Veigar);
list.push(Vel_Koz);
list.push(Vex);
list.push(Vi);
list.push(Viego);
list.push(Viktor);
list.push(Vladimir);
list.push(Volibear);
list.push(Warwick);
list.push(Wukong);
list.push(Xayah);
list.push(Xerath);
list.push(Xin_Zhao);
list.push(Yasuo);
list.push(Yone);
list.push(Yorick);
list.push(Yuumi);
list.push(Zac);
list.push(Zed);
list.push(Zeri);
list.push(Ziggs);
list.push(Zilean);
list.push(Zoe);
list.push(Zyra);
