list = [];
const Aatrox = new Champion("Aatrox", false, false, false, false, false, true, false, false, false, false, false, [""], "icons\\icon (1).png");
const Ahri = new Champion("Ahri", false, false, false, false, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (2).png");
const Akali = new Champion("Akali", false, false, false, false, false, false, false, false, true, false, false, ["ionia"], "icons\\icon (3).png");
const Akshan = new Champion("Akshan", false, true, true, false, false, false, false, true, true, false, false, ["shurima"], "icons\\icon (4).png");
const Alistar = new Champion("Alistar", false, false, false, true, true, true, false, true, false, false, false, [""], "icons\\icon (5).png");
const Amumu = new Champion("Amumu", true, false, false, false, false, true, false, false, false, false, false, ["shurima"], "icons\\icon (6).png");
const Anivia = new Champion("Anivia", false, false, false, false, false, true, false, true, false, false, true, ["freljord"], "icons\\icon (7).png");
const Annie = new Champion("Annie", true, false, false, true, false, false, false, false, false, true, false, [""], "icons\\icon (8).png");
const Aphelios = new Champion("Aphelios", false, false, false, false, false, false, false, false, false, false, false, ["targon"], "icons\\icon (9).png");
const Ashe = new Champion("Ashe", false, true, true, false, false, false, false, false, false, false, false, ["freljord"], "icons\\icon (10).png");
const Aurelion_Sol = new Champion("Aurelion Sol", true, false, false, false, true, true, false, false, false, false, false, ["targon"], "icons\\icon (11).png");
const Azir = new Champion("Azir", true, true, false, false, true, false, false, false, false, true, true, ["shurima"], "icons\\icon (12).png");
const Bard = new Champion("Bard", true, false, true, true, false, true, false, true, false, false, false, [""], "icons\\icon (13).png");
const Bel_Veth = new Champion("Bel'Veth", true, false, false, false, false, false, false, true, false, false, false, ["void"], "icons\\icon (14).png");
const Blitzcrank = new Champion("Blitzcrank", true, false, false, false, true, true, false, false, false, false, false, ["zaun"], "icons\\icon (15).png");
const Brand = new Champion("Brand", false, false, false, false, false, false, false, false, false, false, false, [""], "icons\\icon (16).png");
const Braum = new Champion("Braum", true, false, false, false, false, true, false, true, false, false, false, ["freljord"], "icons\\icon (17).png");
const Caitlyn = new Champion("Caitlyn", false, true, true, false, false, false, true, false, false, false, false, ["piltover"], "icons\\icon (18).png");
const Camille = new Champion("Camille", false, false, false, false, false, true, false, false, false, false, false, ["piltover"], "icons\\icon (19).png");
const Cassiopeia = new Champion("Cassiopeia", true, false, false, false, false, false, false, false, false, false, false, ["noxus"], "icons\\icon (20).png");
const Cho_Gath = new Champion("Cho'Gath", false, true, false, false, false, false, false, false, false, false, false, ["void"], "icons\\icon (21).png");
const Corki = new Champion("Corki", true, true, false, false, false, false, false, false, false, false, false, ["bandleCity", "piltover"], "icons\\icon (22).png");
const Darius = new Champion("Darius", false, false, false, false, true, false, false, false, false, false, false, ["noxus"], "icons\\icon (23).png");
const Diana = new Champion("Diana", true, false, false, false, false, false, false, false, false, false, false, ["targon"], "icons\\icon (24).png");
const Dr_Mundo = new Champion("Dr. Mundo", false, true, false, false, false, false, false, false, false, false, false, ["zaun"], "icons\\icon (25).png");
const Draven = new Champion("Draven", true, false, true, false, false, false, false, false, false, false, false, ["noxus"], "icons\\icon (26).png");
const Ekko = new Champion("Ekko", true, false, false, false, false, false, false, true, false, false, false, ["zaun"], "icons\\icon (27).png");
const Elise = new Champion("Elise", false, false, false, false, false, false, false, true, false, true, false, ["shadowIsles"], "icons\\icon (28).png");
const Evelynn = new Champion("Evelynn", false, false, false, false, false, false, false, true, true, false, false, ["shadowIsles"], "icons\\icon (29).png");
const Ezreal = new Champion("Ezreal", true, true, true, false, false, false, false, false, false, false, false, ["piltover"], "icons\\icon (30).png");
const Fiddlesticks = new Champion("Fiddlesticks", true, false, false, false, false, false, false, false, false, true, false, ["shadowIsles"], "icons\\icon (31).png");
const Fiora = new Champion("Fiora", false, false, false, true, false, false, false, true, false, false, false, ["demacia"], "icons\\icon (32).png");
const Fizz = new Champion("Fizz", true, false, false, false, false, false, false, true, false, false, false, ["bilgewater", "bandleCity"], "icons\\icon (33).png");
const Galio = new Champion("Galio", true, false, true, true, false, true, false, false, false, false, false, ["demacia"], "icons\\icon (34).png");
const Gangplank = new Champion("Gangplank", true, true, true, false, false, false, true, false, false, false, false, ["bilgewater"], "icons\\icon (35).png");
const Garen = new Champion("Garen", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (36).png");
const Gnar = new Champion("Gnar", true, false, false, false, true, true, false, false, false, false, false, ["bandleCity", "freljord"], "icons\\icon (37).png");
const Gragas = new Champion("Gragas", true, false, false, false, true, true, false, false, false, false, false, ["freljord"], "icons\\icon (38).png");
const Graves = new Champion("Graves", true, false, false, false, false, false, false, false, false, false, false, ["bilgewater"], "icons\\icon (39).png");
const Gwen = new Champion("Gwen", false, false, false, false, false, false, false, true, false, false, false, ["shadowIsles"], "icons\\icon (40).png");
const Hecarim = new Champion("Hecarim", true, false, false, false, true, true, false, false, false, false, false, ["shadowIsles"], "icons\\icon (41).png");
const Heimerdinger = new Champion("Heimerdinger", true, false, false, false, false, false, false, false, false, true, false, ["bandleCity", "piltover"], "icons\\icon (42).png");
const Illaoi = new Champion("Illaoi", true, false, false, false, false, false, false, false, false, true, false, ["bilgewater"], "icons\\icon (43).png");
const Irelia = new Champion("Irelia", false, false, false, false, false, false, false, false, false, false, true, ["ionia"], "icons\\icon (44).png");
const Ivern = new Champion("Ivern", false, false, false, true, false, true, false, false, false, true, true, ["ionia"], "icons\\icon (45).png");
const Janna = new Champion("Janna", true, false, false, true, true, true, false, false, false, false, false, ["zaun"], "icons\\icon (46).png");
const Jarvan_IV = new Champion("Jarvan IV", true, false, false, false, false, true, false, false, false, false, true, ["demacia"], "icons\\icon (47).png");
const Jax = new Champion("Jax", false, false, false, false, false, false, false, true, false, false, false, [""], "icons\\icon (48).png");
const Jayce = new Champion("Jayce", false, true, false, false, true, false, false, false, false, false, false, ["piltover"], "icons\\icon (49).png");
const Jhin = new Champion("Jhin", false, true, true, false, false, false, true, false, false, false, false, ["ionia"], "icons\\icon (50).png");
const Jinx = new Champion("Jinx", true, true, true, false, false, false, true, false, false, false, false, ["zaun"], "icons\\icon (51).png");
const Kai_Sa = new Champion("Kai'Sa", false, true, true, false, false, false, false, false, true, false, false, ["void"], "icons\\icon (52).png");
const Kalista = new Champion("Kalista", false, false, false, false, false, false, false, true, false, true, false, ["shadowIsles"], "icons\\icon (53).png");
const Karma = new Champion("Karma", false, true, false, true, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (54).png");
const Karthus = new Champion("Karthus", true, false, true, false, false, false, false, true, false, false, false, ["shadowIsles"], "icons\\icon (55).png");
const Kassadin = new Champion("Kassadin", false, false, false, false, false, false, false, false, false, false, false, ["void"], "icons\\icon (56).png");
const Katarina = new Champion("Katarina", true, false, false, false, false, false, false, false, false, false, false, ["noxus"], "icons\\icon (57).png");
const Kayle = new Champion("Kayle", true, false, false, true, false, false, false, true, false, false, false, ["demacia"], "icons\\icon (58).png");
const Kayn = new Champion("Kayn", false, false, false, false, false, false, false, true, false, false, false, ["ionia"], "icons\\icon (59).png");
const Kennen = new Champion("Kennen", true, false, false, false, false, false, false, false, false, false, false, ["bandleCity", "ionia"], "icons\\icon (60).png");
const Kha_Zix = new Champion("Kha'Zix", false, false, false, false, false, false, false, false, true, false, false, ["void"], "icons\\icon (61).png");
const Kindred = new Champion("Kindred", false, false, false, true, false, false, false, true, false, true, false, [""], "icons\\icon (62).png");
const Kled = new Champion("Kled", false, true, true, false, true, true, false, true, false, false, false, ["bandleCity"], "icons\\icon (63).png");
const Kog_Maw = new Champion("Kog'Maw", false, true, false, false, false, false, false, true, false, false, false, ["void"], "icons\\icon (64).png");
const LeBlanc = new Champion("LeBlanc", false, false, false, false, false, true, false, false, true, false, false, ["noxus"], "icons\\icon (65).png");
const Lee_Sin = new Champion("Lee Sin", false, false, false, true, true, false, false, false, false, false,  false, ["ionia"], "icons\\icon (66).png");
const Leona = new Champion("Leona", true, false, false, false, false, true, false, false, false, false, false, ["targon"], "icons\\icon (67).png");
const Lillia = new Champion("Lillia", false, false, true, false, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (68).png");
const Lissandra = new Champion("Lissandra", true, false, false, false, false, true, false, true, false, true, false, ["freljord"], "icons\\icon (69).png");
const Lucian = new Champion("Lucian", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (70).png");
const Lulu = new Champion("Lulu", false, false, false, true, false, true, false, false, false, false, false, ["bandleCity"], "icons\\icon (71).png");
const Lux = new Champion("Lux", true, true, true, true, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (72).png");
const Malphite = new Champion("Malphite", true, false, false, false, false, false, false, false, false, false, false, ["ixtal"], "icons\\icon (73).png");
const Malzahar = new Champion("Malzahar", false, false, false, false, false, false, false, true, false, true, false, ["void"], "icons\\icon (74).png");
const Maokai = new Champion("Maokai", true, true, true, false, true, true, true, true, false, true, false, ["shadowIsles"], "icons\\icon (75).png");
const Master_Yi = new Champion("Master Yi", false, false, false, false, false, false, false, true, false, false, false, ["ionia"], "icons\\icon (76).png");
const Miss_Fortune = new Champion("Miss Fortune", true, false, false, false, false, false, false, false, false, false, false, ["bilgewater"], "icons\\icon (78).png");
const Mordekaiser = new Champion("Mordekaiser", false, false, false, false, true, false, false, false, false, false, false, [""], "icons\\icon (79).png");
const Morgana = new Champion("Morgana", true, false, false, true, false, true, false, false, false, false, false, ["demacia"], "icons\\icon (80).png");
const Nami = new Champion("Nami", true, false, false, true, false, true, false, false, false, false, false, [""], "icons\\icon (81).png");
const Nasus = new Champion("Nasus", false, false, false, false, false, false, false, false, false, false, false, ["shurima"], "icons\\icon (82).png");
const Nautilus = new Champion("Nautilus", false, false, false, false, true, true, false, false, false, false, false, ["bilgewater"], "icons\\icon (83).png");
const Neeko = new Champion("Neeko", true, false, false, false, false, true, false, false, true, true, false, ["ixtal"], "icons\\icon (84).png");
const Nidalee = new Champion("Nidalee", false, true, false, true, false, false, true, false, false, false, false, ["ixtal"], "icons\\icon (85).png");
const Nilah = new Champion("Nilah", false, false, false, false, false, false, false, false, false, false, false, ["bilgewater"], "icons\\B3CB47C2-CF7D-4113-900B-9DFD8AADA649.webp");
const Nocturne = new Champion("Nocturne", false, false, true, false, false, false, false, false, true, false, false, [""], "icons\\icon (86).png");
const Nunu_Willump = new Champion("Nunu & Willump", true, false, false, false, false, true, false, false, false, false, false, ["freljord"], "icons\\icon (87).png");
const Olaf = new Champion("Olaf", false, false, false, false, false, false, false, true, false, false, false, ["freljord"], "icons\\icon (88).png");
const Orianna = new Champion("Orianna", true, false, false, true, true, false, false, false, false, true, false, ["piltover"], "icons\\icon (89).png");
const Ornn = new Champion("Ornn", true, false, false, false, false, true, false, false, false, false, true, ["freljord"], "icons\\icon (90).png");
const Pantheon = new Champion("Pantheon", true, true, true, false, false, false, false, true, false, false, false, ["targon"], "icons\\icon (91).png");
const Poppy = new Champion("Poppy", false, false, false, false, true, true, false, false, false, false, false, ["bandleCity", "demacia"], "icons\\icon (92).png");
const Pyke = new Champion("Pyke", false, false, false, false, true, true, false, false, true, false, false, ["bilgewater"], "icons\\icon (93).png");
const Qiyana = new Champion("Qiyana", true, false, false, false, false, true, false, false, true, false, false, ["ixtal"], "icons\\icon (94).png");
const Quinn = new Champion("Quinn", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (95).png");
const Rakan = new Champion("Rakan", true, false, false, true, false, false, false, true, false, false, false, ["ionia"], "icons\\icon (96).png");
const Rammus = new Champion("Rammus", true, false, false, false, false, true, false, false, false, false, false, ["shurima"], "icons\\icon (97).png");
const Rek_Sai = new Champion("Rek'Sai", false, false, false, false, false, false, false, false, false, false, false, ["void"], "icons\\icon (98).png");
const Rell = new Champion("Rell", true, false, false, true, true, true, false, false, false, false, false, ["noxus"], "icons\\icon (99).png");
const Renata_Glasc = new Champion("Renata Glasc", true, false, false, true, false, true, false, true, false, false, false, ["zaun"], "icons\\icon (161).png");
const Renekton = new Champion("Renekton", false, false, false, false, false, false, false, false, false, false, false, ["shurima"], "icons\\icon (100).png");
const Rengar = new Champion("Rengar", false, false, false, false, false, false, false, false, true, false, false, ["ixtal"], "icons\\icon (101).png");
const Riven = new Champion("Riven", true, false, false, false, false, true, false, false, false, false, false, ["noxus"], "icons\\icon (103).png");
const Rumble = new Champion("Rumble", true, false, false, false, false, false, false, false, false, false, false, ["bandleCity"], "icons\\icon (104).png");
const Ryze = new Champion("Ryze", false, false, true, false, false, false, false, false, false, false, false, [""], "icons\\icon (105).png");
const Samira = new Champion("Samira", true, false, false, false, false, false, false, false, false, false, false, ["noxus"], "icons\\icon (106).png");
const Sejuani = new Champion("Sejuani", true, false, false, false, false, true, false, false, false, false, false, ["freljord"], "icons\\icon (107).png");
const Senna = new Champion("Senna", true, true, true, true, false, false, false, false, true, false, false, ["shadowIsles"], "icons\\icon (108).png");
const Seraphine = new Champion("Seraphine", true, true, false, true, false, true, false, false, false, false, false, ["piltover"], "icons\\icon (109).png");
const Sett = new Champion("Sett", true, false, false, false, true, true, false, false, false, false, false, ["ionia"], "icons\\icon (110).png");
const Shaco = new Champion("Shaco", false, false, false, false, false, true, true, false, true, true, false, [""], "icons\\icon (111).png");
const Shen = new Champion("Shen", false, false, true, true, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (113).png");
const Shyvana = new Champion("Shyvana", false, true, false, false, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (114).png");
const Singed = new Champion("Singed", false, false, false, false, true, true, false, false, false, false, false, ["zaun"], "icons\\icon (115).png");
const Sion = new Champion("Sion", false, false, true, false, false, true, false, true, false, false, false, ["noxus"], "icons\\icon (116).png");
const Sivir = new Champion("Sivir", false, true, false, false, false, false, false, false, false, false, false, ["shurima"], "icons\\icon (117).png");
const Skarner = new Champion("Skarner", false, false, false, false, true, true, false, false, false, false, false, ["shurima"], "icons\\icon (118).png");
const Sona = new Champion("Sona", true, false, false, true, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (119).png");
const Soraka = new Champion("Soraka", false, false, true, true, false, false, false, false, false, false, false, ["targon"], "icons\\icon (120).png");
const Swain = new Champion("Swain", true, false, true, false, true, false, false, false, false, false, false, ["noxus"], "icons\\icon (121).png");
const Sylas = new Champion("Sylas", false, false, false, false, false, false, false, false, false, false, false, ["demacia"], "icons\\icon (122).png");
const Syndra = new Champion("Syndra", false, false, false, false, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (123).png");
const Tahm_Kench = new Champion("Tahm Kench", false, false, false, true, true, true, false, true, false, false, false, ["bilgewater"], "icons\\icon (124).png");
const Taliyah = new Champion("Taliyah", false, true, true, false, true, false, false, false, false, false, true, ["shurima"], "icons\\icon (125).png");
const Talon = new Champion("Talon", true, false, false, false, false, false, false, false, true, false, false, ["noxus"], "icons\\icon (126).png");
const Taric = new Champion("Taric", false, false, false, true, false, false, false, true, false, false, false, ["targon"], "icons\\icon (127).png");
const Teemo = new Champion("Teemo", false, false, false, false, false, false, true, false, true, false, false, ["bandleCity"], "icons\\icon (128).png");
const Thresh = new Champion("Thresh", false, false, false, true, true, true, false, false, false, false, false, ["shadowIsles"], "icons\\icon (129).png");
const Tristana = new Champion("Tristana", false, false, false, false, true, false, false, false, false, false, false, ["bandleCity"], "icons\\icon (130).png");
const Trundle = new Champion("Trundle", false, false, false, false, false, false, false, false, false, false, true, ["freljord"], "icons\\icon (131).png");
const Tryndamere = new Champion("Tryndamere", false, false, false, false, false, false, false, true, false, false, false, ["freljord"], "icons\\icon (132).png");
const Twisted_Fate = new Champion("Twisted Fate", false, true, true, false, false, false, false, false, false, false, false, ["bilgewater"], "icons\\icon (133).png");
const Twitch = new Champion("Twitch", true, false, false, false, false, false, false, false, true, false, false, ["zaun"], "icons\\icon (134).png");
const Udyr = new Champion("Udyr", false, false, false, false, false, false, false, false, false, false, false, ["freljord"], "icons\\icon (135).png");
const Urgot = new Champion("Urgot", false, false, false, false, true, true, false, false, false, false, false, ["zaun"], "icons\\icon (136).png");
const Varus = new Champion("Varus", false, true, false, false, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (137).png");
const Vayne = new Champion("Vayne", false, false, false, false, true, false, false, false, true, false, false, ["demacia"], "icons\\icon (138).png");
const Veigar = new Champion("Veigar", false, false, false, false, false, false, false, false, false, false, true, ["bandleCity"], "icons\\icon (139).png");
const Vel_Koz = new Champion("Vel'Koz", true, true, false, false, false, false, false, false, false, false, false, ["void"], "icons\\icon (140).png");
const Vex = new Champion("Vex", false, true, true, false, false, false, false, false, false, false, false, ["bandleCity"], "icons\\icon (163).png");
const Vi = new Champion("Vi", false, false, false, false, false, true, false, false, false, false, false, ["piltover"], "icons\\icon (141).png");
const Viego = new Champion("Viego", false, false, false, false, false, false, false, false, true, false, false, ["shadowIsles"], "icons\\icon (142).png");
const Viktor = new Champion("Viktor", true, true, false, false, false, false, false, false, false, false, false, ["zaun"], "icons\\icon (143).png");
const Vladimir = new Champion("Vladimir", true, false, false, false, false, false, false, true, false, false, false, ["noxus"], "icons\\icon (144).png");
const Volibear = new Champion("Volibear", true, false, false, false, false, false, false, false, false, false, false, ["freljord"], "icons\\icon (145).png");
const Warwick = new Champion("Warwick", false, false, false, false, false, true, false, false, false, false, false, ["zaun"], "icons\\icon (146).png");
const Wukong = new Champion("Wukong", false, false, false, false, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (147).png");
const Xayah = new Champion("Xayah", true, true, false, false, false, false, false, false, false, false, false, ["ionia"], "icons\\icon (148).png");
const Xerath = new Champion("Xerath", false, true, true, false, false, false, false, false, false, false, false, ["shurima"], "icons\\icon (149).png");
const Xin_Zhao = new Champion("Xin Zhao", true, false, false, false, true, true, false, true, false, false, false, ["demacia"], "icons\\icon (150).png");
const Yasuo = new Champion("Yasuo", false, false, false, false, false, true, false, false, false, false, false, ["ionia"], "icons\\icon (151).png");
const Yone = new Champion("Yone", true, false, false, false, true, true, false, false, false, false, false, ["ionia"], "icons\\icon (152).png");
const Yorick = new Champion("Yorick", false, false, false, false, false, false, false, false, false, true, true, ["shadowIsles"], "icons\\icon (153).png");
const Yuumi = new Champion("Yuumi", true, true, false, true, false, false, false, true, false, false, false, ["bandleCity"], "icons\\icon (154).png");
const Zac = new Champion("Zac", true, false, false, false, true, true, false, true, false, false, false, ["zaun"], "icons\\icon (155).png");
const Zed = new Champion("Zed", false, false, false, false, false, false, false, true, false, true, false, ["ionia"], "icons\\icon (156).png");
const Zeri = new Champion("Zeri", false, false, false, false, false, false, false, false, false, false, false, ["zaun"], "icons\\icon (162).png");
const Ziggs = new Champion("Ziggs", true, true, true, false, true, false, true, false, false, false, false, ["bandleCity"], "icons\\icon (157).png");
const Zilean = new Champion("Zilean", false, false, false, true, false, false, false, true, false, false, false, ["shurima"], "icons\\icon (158).png");
const Zoe = new Champion("Zoe", false, true, false, false, false, false, false, false, false, false, false, ["targon"], "icons\\icon (159).png");
const Zyra = new Champion("Zyra", true, false, false, false, false, true, true, false, false, true, false, ["ixtal"], "icons\\icon (160).png");
list.push(Aatrox);
list.push(Ahri);
list.push(Akali);
list.push(Akshan);
list.push(Alistar);
list.push(Amumu);
list.push(Anivia);
list.push(Annie);
list.push(Aphelios);
list.push(Ashe);
list.push(Aurelion_Sol);
list.push(Azir);
list.push(Bard);
list.push(Bel_Veth);
list.push(Blitzcrank);
list.push(Brand);
list.push(Braum);
list.push(Caitlyn);
list.push(Camille);
list.push(Cassiopeia);
list.push(Cho_Gath);
list.push(Corki);
list.push(Darius);
list.push(Diana);
list.push(Dr_Mundo);
list.push(Draven);
list.push(Ekko);
list.push(Elise);
list.push(Evelynn);
list.push(Ezreal);
list.push(Fiddlesticks);
list.push(Fiora);
list.push(Fizz);
list.push(Galio);
list.push(Gangplank);
list.push(Garen);
list.push(Gnar);
list.push(Gragas);
list.push(Graves);
list.push(Gwen);
list.push(Hecarim);
list.push(Heimerdinger);
list.push(Illaoi);
list.push(Irelia);
list.push(Ivern);
list.push(Janna);
list.push(Jarvan_IV);
list.push(Jax);
list.push(Jayce);
list.push(Jhin);
list.push(Jinx);
list.push(Kai_Sa);
list.push(Kalista);
list.push(Karma);
list.push(Karthus);
list.push(Kassadin);
list.push(Katarina);
list.push(Kayle);
list.push(Kayn);
list.push(Kennen);
list.push(Kha_Zix);
list.push(Kindred);
list.push(Kled);
list.push(Kog_Maw);
list.push(LeBlanc);
list.push(Lee_Sin);
list.push(Leona);
list.push(Lillia);
list.push(Lissandra);
list.push(Lucian);
list.push(Lulu);
list.push(Lux);
list.push(Malphite);
list.push(Malzahar);
list.push(Maokai);
list.push(Master_Yi);
list.push(Miss_Fortune);
list.push(Mordekaiser);
list.push(Morgana);
list.push(Nami);
list.push(Nasus);
list.push(Nautilus);
list.push(Neeko);
list.push(Nidalee);
list.push(Nilah);
list.push(Nocturne);
list.push(Nunu_Willump);
list.push(Olaf);
list.push(Orianna);
list.push(Ornn);
list.push(Pantheon);
list.push(Poppy);
list.push(Pyke);
list.push(Qiyana);
list.push(Quinn);
list.push(Rakan);
list.push(Rammus);
list.push(Rek_Sai);
list.push(Rell);
list.push(Renata_Glasc);
list.push(Renekton);
list.push(Rengar);
list.push(Riven);
list.push(Rumble);
list.push(Ryze);
list.push(Samira);
list.push(Sejuani);
list.push(Senna);
list.push(Seraphine);
list.push(Sett);
list.push(Shaco);
list.push(Shen);
list.push(Shyvana);
list.push(Singed);
list.push(Sion);
list.push(Sivir);
list.push(Skarner);
list.push(Sona);
list.push(Soraka);
list.push(Swain);
list.push(Sylas);
list.push(Syndra);
list.push(Tahm_Kench);
list.push(Taliyah);
list.push(Talon);
list.push(Taric);
list.push(Teemo);
list.push(Thresh);
list.push(Tristana);
list.push(Trundle);
list.push(Tryndamere);
list.push(Twisted_Fate);
list.push(Twitch);
list.push(Udyr);
list.push(Urgot);
list.push(Varus);
list.push(Vayne);
list.push(Veigar);
list.push(Vel_Koz);
list.push(Vex);
list.push(Vi);
list.push(Viego);
list.push(Viktor);
list.push(Vladimir);
list.push(Volibear);
list.push(Warwick);
list.push(Wukong);
list.push(Xayah);
list.push(Xerath);
list.push(Xin_Zhao);
list.push(Yasuo);
list.push(Yone);
list.push(Yorick);
list.push(Yuumi);
list.push(Zac);
list.push(Zed);
list.push(Zeri);
list.push(Ziggs);
list.push(Zilean);
list.push(Zoe);
list.push(Zyra);
