list = [];
const Aatrox = new Champion("Aatrox", true, false, false, false, false, true, false, false, false, false, false, "null");
const Ahri = new Champion("Ahri", true, true, false, false, false, false, false, false, false, false, false, "ionia");
const Akali = new Champion("Akali", true, true, false, false, false, true, false, false, false, false, false, "null");
const Akshan = new Champion("Akshan", false, false, false, false, false, true, false, false, false, false, false, "null");
const Alistar = new Champion("Alistar", false, false, false, false, false, true, false, false, false, false, false, "null");
const Amumu = new Champion("Amumu", false, false, false, false, false, true, false, false, false, false, false, "null");
const Anivia = new Champion("Anivia", false, false, false, false, false, true, false, false, false, false, false, "null");
const Annie = new Champion("Annie", false, false, false, false, false, true, false, false, false, false, false, "null");
const Aphelios = new Champion("Aphelios", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ashe = new Champion("Ashe", false, false, false, false, false, true, false, false, false, false, false, "null");
const Aurelion_Sol = new Champion("Aurelion Sol", false, false, false, false, false, true, false, false, false, false, false, "null");
const Azir = new Champion("Azir", false, false, false, false, false, true, false, false, false, false, false, "null");
const Bard = new Champion("Bard", false, false, false, false, false, true, false, false, false, false, false, "null");
const Bel_Veth = new Champion("Bel'Veth", false, false, false, false, false, true, false, false, false, false, false, "null");
const Blitzcrank = new Champion("Blitzcrank", false, false, false, false, false, true, false, false, false, false, false, "null");
const Brand = new Champion("Brand", false, false, false, false, false, true, false, false, false, false, false, "null");
const Braum = new Champion("Braum", false, false, false, false, false, true, false, false, false, false, false, "null");
const Caitlyn = new Champion("Caitlyn", false, false, false, false, false, true, false, false, false, false, false, "null");
const Camille = new Champion("Camille", false, false, false, false, false, true, false, false, false, false, false, "null");
const Cassiopeia = new Champion("Cassiopeia", false, false, false, false, false, true, false, false, false, false, false, "null");
const Cho_Gath = new Champion("Cho'Gath", false, false, false, false, false, true, false, false, false, false, false, "null");
const Corki = new Champion("Corki", false, false, false, false, false, true, false, false, false, false, false, "null");
const Darius = new Champion("Darius", false, false, false, false, false, true, false, false, false, false, false, "null");
const Diana = new Champion("Diana", false, false, false, false, false, true, false, false, false, false, false, "null");
const Dr_Mundo = new Champion("Dr. Mundo", false, false, false, false, false, true, false, false, false, false, false, "null");
const Draven = new Champion("Draven", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ekko = new Champion("Ekko", false, false, false, false, false, true, false, false, false, false, false, "null");
const Elise = new Champion("Elise", false, false, false, false, false, true, false, false, false, false, false, "null");
const Evelynn = new Champion("Evelynn", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ezreal = new Champion("Ezreal", false, false, false, false, false, true, false, false, false, false, false, "null");
const Fiddlesticks = new Champion("Fiddlesticks", false, false, false, false, false, true, false, false, false, false, false, "null");
const Fiora = new Champion("Fiora", false, false, false, false, false, true, false, false, false, false, false, "null");
const Fizz = new Champion("Fizz", false, false, false, false, false, true, false, false, false, false, false, "null");
const Galio = new Champion("Galio", false, false, false, false, false, true, false, false, false, false, false, "null");
const Gangplank = new Champion("Gangplank", false, false, false, false, false, true, false, false, false, false, false, "null");
const Garen = new Champion("Garen", false, false, false, false, false, true, false, false, false, false, false, "null");
const Gnar = new Champion("Gnar", false, false, false, false, false, true, false, false, false, false, false, "null");
const Gragas = new Champion("Gragas", false, false, false, false, false, true, false, false, false, false, false, "null");
const Graves = new Champion("Graves", false, false, false, false, false, true, false, false, false, false, false, "null");
const Gwen = new Champion("Gwen", false, false, false, false, false, true, false, false, false, false, false, "null");
const Hecarim = new Champion("Hecarim", false, false, false, false, false, true, false, false, false, false, false, "null");
const Heimerdinger = new Champion("Heimerdinger", false, false, false, false, false, true, false, false, false, false, false, "null");
const Illaoi = new Champion("Illaoi", false, false, false, false, false, true, false, false, false, false, false, "null");
const Irelia = new Champion("Irelia", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ivern = new Champion("Ivern", false, false, false, false, false, true, false, false, false, false, false, "null");
const Janna = new Champion("Janna", false, false, false, false, false, true, false, false, false, false, false, "null");
const Jarvan_IV = new Champion("Jarvan IV", false, false, false, false, false, true, false, false, false, false, false, "null");
const Jax = new Champion("Jax", false, false, false, false, false, true, false, false, false, false, false, "null");
const Jayce = new Champion("Jayce", false, false, false, false, false, true, false, false, false, false, false, "null");
const Jhin = new Champion("Jhin", false, false, false, false, false, true, false, false, false, false, false, "null");
const Jinx = new Champion("Jinx", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kai_Sa = new Champion("Kai'Sa", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kalista = new Champion("Kalista", false, false, false, false, false, true, false, false, false, false, false, "null");
const Karma = new Champion("Karma", false, false, false, false, false, true, false, false, false, false, false, "null");
const Karthus = new Champion("Karthus", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kassadin = new Champion("Kassadin", false, false, false, false, false, true, false, false, false, false, false, "null");
const Katarina = new Champion("Katarina", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kayle = new Champion("Kayle", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kayn = new Champion("Kayn", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kennen = new Champion("Kennen", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kha_Zix = new Champion("Kha'Zix", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kindred = new Champion("Kindred", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kled = new Champion("Kled", false, false, false, false, false, true, false, false, false, false, false, "null");
const Kog_Maw = new Champion("Kog'Maw", false, false, false, false, false, true, false, false, false, false, false, "null");
const LeBlanc = new Champion("LeBlanc", false, false, false, false, false, true, false, false, false, false, false, "null");
const Lee_Sin = new Champion("Lee Sin", false, false, false, false, false, true, false, false, false, false, false, "null");
const Leona = new Champion("Leona", false, false, false, false, false, true, false, false, false, false, false, "null");
const Lillia = new Champion("Lillia", false, false, false, false, false, true, false, false, false, false, false, "null");
const Lissandra = new Champion("Lissandra", false, false, false, false, false, true, false, false, false, false, false, "null");
const Lucian = new Champion("Lucian", false, false, false, false, false, true, false, false, false, false, false, "null");
const Lulu = new Champion("Lulu", false, false, false, false, false, true, false, false, false, false, false, "null");
const Lux = new Champion("Lux", false, false, false, false, false, true, false, false, false, false, false, "null");
const Malphite = new Champion("Malphite", false, false, false, false, false, true, false, false, false, false, false, "null");
const Malzahar = new Champion("Malzahar", false, false, false, false, false, true, false, false, false, false, false, "null");
const Maokai = new Champion("Maokai", false, false, false, false, false, true, false, false, false, false, false, "null");
const Master_Yi = new Champion("Master Yi", false, false, false, false, false, true, false, false, false, false, false, "null");
const Miss_Fortune = new Champion("Miss Fortune", false, false, false, false, false, true, false, false, false, false, false, "null");
const Mordekaiser = new Champion("Mordekaiser", false, false, false, false, false, true, false, false, false, false, false, "null");
const Morgana = new Champion("Morgana", false, false, false, false, false, true, false, false, false, false, false, "null");
const Nami = new Champion("Nami", false, false, false, false, false, true, false, false, false, false, false, "null");
const Nasus = new Champion("Nasus", false, false, false, false, false, true, false, false, false, false, false, "null");
const Nautilus = new Champion("Nautilus", false, false, false, false, false, true, false, false, false, false, false, "null");
const Neeko = new Champion("Neeko", false, false, false, false, false, true, false, false, false, false, false, "null");
const Nidalee = new Champion("Nidalee", false, false, false, false, false, true, false, false, false, false, false, "null");
const Nocturne = new Champion("Nocturne", false, false, false, false, false, true, false, false, false, false, false, "null");
const Nunu_Willump = new Champion("Nunu & Willump", false, false, false, false, false, true, false, false, false, false, false, "null");
const Olaf = new Champion("Olaf", false, false, false, false, false, true, false, false, false, false, false, "null");
const Orianna = new Champion("Orianna", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ornn = new Champion("Ornn", false, false, false, false, false, true, false, false, false, false, false, "null");
const Pantheon = new Champion("Pantheon", false, false, false, false, false, true, false, false, false, false, false, "null");
const Poppy = new Champion("Poppy", false, false, false, false, false, true, false, false, false, false, false, "null");
const Pyke = new Champion("Pyke", false, false, false, false, false, true, false, false, false, false, false, "null");
const Qiyana = new Champion("Qiyana", false, false, false, false, false, true, false, false, false, false, false, "null");
const Quinn = new Champion("Quinn", false, false, false, false, false, true, false, false, false, false, false, "null");
const Rakan = new Champion("Rakan", false, false, false, false, false, true, false, false, false, false, false, "null");
const Rammus = new Champion("Rammus", false, false, false, false, false, true, false, false, false, false, false, "null");
const Rek_Sai = new Champion("Rek'Sai", false, false, false, false, false, true, false, false, false, false, false, "null");
const Rell = new Champion("Rell", false, false, false, false, false, true, false, false, false, false, false, "null");
const Renata_Glasc = new Champion("Renata Glasc", false, false, false, false, false, true, false, false, false, false, false, "null");
const Renekton = new Champion("Renekton", false, false, false, false, false, true, false, false, false, false, false, "null");
const Rengar = new Champion("Rengar", false, false, false, false, false, true, false, false, false, false, false, "null");
const Riven = new Champion("Riven", false, false, false, false, false, true, false, false, false, false, false, "null");
const Rumble = new Champion("Rumble", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ryze = new Champion("Ryze", false, false, false, false, false, true, false, false, false, false, false, "null");
const Samira = new Champion("Samira", false, false, false, false, false, true, false, false, false, false, false, "null");
const Sejuani = new Champion("Sejuani", false, false, false, false, false, true, false, false, false, false, false, "null");
const Senna = new Champion("Senna", false, false, false, false, false, true, false, false, false, false, false, "null");
const Seraphine = new Champion("Seraphine", false, false, false, false, false, true, false, false, false, false, false, "null");
const Sett = new Champion("Sett", false, false, false, false, false, true, false, false, false, false, false, "null");
const Shaco = new Champion("Shaco", false, false, false, false, false, true, false, false, false, false, false, "null");
const Shen = new Champion("Shen", false, false, false, false, false, true, false, false, false, false, false, "null");
const Shyvana = new Champion("Shyvana", false, false, false, false, false, true, false, false, false, false, false, "null");
const Singed = new Champion("Singed", false, false, false, false, false, true, false, false, false, false, false, "null");
const Sion = new Champion("Sion", false, false, false, false, false, true, false, false, false, false, false, "null");
const Sivir = new Champion("Sivir", false, false, false, false, false, true, false, false, false, false, false, "null");
const Skarner = new Champion("Skarner", false, false, false, false, false, true, false, false, false, false, false, "null");
const Sona = new Champion("Sona", false, false, false, false, false, true, false, false, false, false, false, "null");
const Soraka = new Champion("Soraka", false, false, false, false, false, true, false, false, false, false, false, "null");
const Swain = new Champion("Swain", false, false, false, false, false, true, false, false, false, false, false, "null");
const Sylas = new Champion("Sylas", false, false, false, false, false, true, false, false, false, false, false, "null");
const Syndra = new Champion("Syndra", false, false, false, false, false, true, false, false, false, false, false, "null");
const Tahm_Kench = new Champion("Tahm Kench", false, false, false, false, false, true, false, false, false, false, false, "null");
const Taliyah = new Champion("Taliyah", false, false, false, false, false, true, false, false, false, false, false, "null");
const Talon = new Champion("Talon", false, false, false, false, false, true, false, false, false, false, false, "null");
const Taric = new Champion("Taric", false, false, false, false, false, true, false, false, false, false, false, "null");
const Teemo = new Champion("Teemo", false, false, false, false, false, true, false, false, false, false, false, "null");
const Thresh = new Champion("Thresh", false, false, false, false, false, true, false, false, false, false, false, "null");
const Tristana = new Champion("Tristana", false, false, false, false, false, true, false, false, false, false, false, "null");
const Trundle = new Champion("Trundle", false, false, false, false, false, true, false, false, false, false, false, "null");
const Tryndamere = new Champion("Tryndamere", false, false, false, false, false, true, false, false, false, false, false, "null");
const Twisted_Fate = new Champion("Twisted Fate", false, false, false, false, false, true, false, false, false, false, false, "null");
const Twitch = new Champion("Twitch", false, false, false, false, false, true, false, false, false, false, false, "null");
const Udyr = new Champion("Udyr", false, false, false, false, false, true, false, false, false, false, false, "null");
const Urgot = new Champion("Urgot", false, false, false, false, false, true, false, false, false, false, false, "null");
const Varus = new Champion("Varus", false, false, false, false, false, true, false, false, false, false, false, "null");
const Vayne = new Champion("Vayne", false, false, false, false, false, true, false, false, false, false, false, "null");
const Veigar = new Champion("Veigar", false, false, false, false, false, true, false, false, false, false, false, "null");
const Vel_Koz = new Champion("Vel'Koz", false, false, false, false, false, true, false, false, false, false, false, "null");
const Vex = new Champion("Vex", false, false, false, false, false, true, false, false, false, false, false, "null");
const Vi = new Champion("Vi", false, false, false, false, false, true, false, false, false, false, false, "null");
const Viego = new Champion("Viego", false, false, false, false, false, true, false, false, false, false, false, "null");
const Viktor = new Champion("Viktor", false, false, false, false, false, true, false, false, false, false, false, "null");
const Vladimir = new Champion("Vladimir", false, false, false, false, false, true, false, false, false, false, false, "null");
const Volibear = new Champion("Volibear", false, false, false, false, false, true, false, false, false, false, false, "null");
const Warwick = new Champion("Warwick", false, false, false, false, false, true, false, false, false, false, false, "null");
const Wukong = new Champion("Wukong", false, false, false, false, false, true, false, false, false, false, false, "null");
const Xayah = new Champion("Xayah", false, false, false, false, false, true, false, false, false, false, false, "null");
const Xerath = new Champion("Xerath", false, false, false, false, false, true, false, false, false, false, false, "null");
const Xin_Zhao = new Champion("Xin Zhao", false, false, false, false, false, true, false, false, false, false, false, "null");
const Yasuo = new Champion("Yasuo", false, false, false, false, false, true, false, false, false, false, false, "null");
const Yone = new Champion("Yone", false, false, false, false, false, true, false, false, false, false, false, "null");
const Yorick = new Champion("Yorick", false, false, false, false, false, true, false, false, false, false, false, "null");
const Yuumi = new Champion("Yuumi", false, false, false, false, false, true, false, false, false, false, false, "null");
const Zac = new Champion("Zac", false, false, false, false, false, true, false, false, false, false, false, "null");
const Zed = new Champion("Zed", false, false, false, false, false, true, false, false, false, false, false, "null");
const Zeri = new Champion("Zeri", false, false, false, false, false, true, false, false, false, false, false, "null");
const Ziggs = new Champion("Ziggs", false, false, false, false, false, true, false, false, false, false, false, "null");
const Zilean = new Champion("Zilean", false, false, false, false, false, true, false, false, false, false, false, "null");
const Zoe = new Champion("Zoe", false, false, false, false, false, true, false, false, false, false, false, "null");
const Zyra = new Champion("Zyra", false, false, false, false, false, true, false, false, false, false, false, "null");
list.push(Aatrox);
list.push(Ahri);
list.push(Akali);
list.push(Akshan);
list.push(Alistar);
list.push(Amumu);
list.push(Anivia);
list.push(Annie);
list.push(Aphelios);
list.push(Ashe);
list.push(Aurelion_Sol);
list.push(Azir);
list.push(Bard);
list.push(Bel_Veth);
list.push(Blitzcrank);
list.push(Brand);
list.push(Braum);
list.push(Caitlyn);
list.push(Camille);
list.push(Cassiopeia);
list.push(Cho_Gath);
list.push(Corki);
list.push(Darius);
list.push(Diana);
list.push(Dr_Mundo);
list.push(Draven);
list.push(Ekko);
list.push(Elise);
list.push(Evelynn);
list.push(Ezreal);
list.push(Fiddlesticks);
list.push(Fiora);
list.push(Fizz);
list.push(Galio);
list.push(Gangplank);
list.push(Garen);
list.push(Gnar);
list.push(Gragas);
list.push(Graves);
list.push(Gwen);
list.push(Hecarim);
list.push(Heimerdinger);
list.push(Illaoi);
list.push(Irelia);
list.push(Ivern);
list.push(Janna);
list.push(Jarvan_IV);
list.push(Jax);
list.push(Jayce);
list.push(Jhin);
list.push(Jinx);
list.push(Kai_Sa);
list.push(Kalista);
list.push(Karma);
list.push(Karthus);
list.push(Kassadin);
list.push(Katarina);
list.push(Kayle);
list.push(Kayn);
list.push(Kennen);
list.push(Kha_Zix);
list.push(Kindred);
list.push(Kled);
list.push(Kog_Maw);
list.push(LeBlanc);
list.push(Lee_Sin);
list.push(Leona);
list.push(Lillia);
list.push(Lissandra);
list.push(Lucian);
list.push(Lulu);
list.push(Lux);
list.push(Malphite);
list.push(Malzahar);
list.push(Maokai);
list.push(Master_Yi);
list.push(Miss_Fortune);
list.push(Mordekaiser);
list.push(Morgana);
list.push(Nami);
list.push(Nasus);
list.push(Nautilus);
list.push(Neeko);
list.push(Nidalee);
list.push(Nocturne);
list.push(Nunu_Willump);
list.push(Olaf);
list.push(Orianna);
list.push(Ornn);
list.push(Pantheon);
list.push(Poppy);
list.push(Pyke);
list.push(Qiyana);
list.push(Quinn);
list.push(Rakan);
list.push(Rammus);
list.push(Rek_Sai);
list.push(Rell);
list.push(Renata_Glasc);
list.push(Renekton);
list.push(Rengar);
list.push(Riven);
list.push(Rumble);
list.push(Ryze);
list.push(Samira);
list.push(Sejuani);
list.push(Senna);
list.push(Seraphine);
list.push(Sett);
list.push(Shaco);
list.push(Shen);
list.push(Shyvana);
list.push(Singed);
list.push(Sion);
list.push(Sivir);
list.push(Skarner);
list.push(Sona);
list.push(Soraka);
list.push(Swain);
list.push(Sylas);
list.push(Syndra);
list.push(Tahm_Kench);
list.push(Taliyah);
list.push(Talon);
list.push(Taric);
list.push(Teemo);
list.push(Thresh);
list.push(Tristana);
list.push(Trundle);
list.push(Tryndamere);
list.push(Twisted_Fate);
list.push(Twitch);
list.push(Udyr);
list.push(Urgot);
list.push(Varus);
list.push(Vayne);
list.push(Veigar);
list.push(Vel_Koz);
list.push(Vex);
list.push(Vi);
list.push(Viego);
list.push(Viktor);
list.push(Vladimir);
list.push(Volibear);
list.push(Warwick);
list.push(Wukong);
list.push(Xayah);
list.push(Xerath);
list.push(Xin_Zhao);
list.push(Yasuo);
list.push(Yone);
list.push(Yorick);
list.push(Yuumi);
list.push(Zac);
list.push(Zed);
list.push(Zeri);
list.push(Ziggs);
list.push(Zilean);
list.push(Zoe);
list.push(Zyra);